library(tidyverse)
library(naniar)
library(SNFtool)
cna_df = read_tsv("./data/processed_data/cna.csv")
fpkm_df = read_tsv("./data/processed_data/fpkm.csv")
cna_df = as.data.frame(cna_df[, -1])
fpkm_df = as.data.frame(fpkm_df[, -1])

fpkm_df_normalized = standardNormalization(fpkm_df)

cna_Dist = dist2(as.matrix(cna_df), as.matrix(cna_df))
fpkm_Dist = dist2(as.matrix(fpkm_df_normalized), as.matrix(fpkm_df_normalized))
K = 20;		# number of neighbors, usually (10~30)
alpha = 0.5;  	# hyperparameter, usually (0.3~0.8)
T = 15; 	# Number of Iterations, usually (10~20)
W_cna = affinityMatrix(cna_Dist, K, alpha)
W_fpkm = affinityMatrix(fpkm_Dist, K, alpha)
W = SNF(list(W_cna,W_fpkm), K, T)
str(W)
w_df = as_tibble(W)
head(w_df)
write.csv(W, file="./data/processed_data/simlilarity_matrix.csv")
